In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [4]:
# Numpy dimension
a.ndim

1

In [5]:
#Get  shape 
a.shape

(5,)

In [6]:
#Get datatype
a.dtype

dtype('int32')

In [26]:
# Adding 2 to the values in an array
a + 2

array([3, 4, 5, 6, 7])

In [7]:
# To specify the datatype and datasize of the numpy array
b = np.array([1,2,3,4,5], dtype='int16')
b

array([1, 2, 3, 4, 5], dtype=int16)

In [8]:
c = np.array([1.0, 2.1, 3.1, 4.0, 5.0])
c

array([1. , 2.1, 3.1, 4. , 5. ])

In [9]:
#Double data type is 8 while Int data type is 4
c.itemsize

8

In [10]:
a.shape


(5,)

In [41]:
Number = [[1,2,4,6,7,8,9] , [3,4,5,6,0,7,6]]
num = np.array(Number)
num

array([[1, 2, 4, 6, 7, 8, 9],
       [3, 4, 5, 6, 0, 7, 6]])

In [42]:
num.shape

(2, 7)

In [44]:
# Selecting a specific [row, column]
num[0, 4]

7

In [34]:
d = np.array ([[1,2,4,6,7,8,9] , [3,4,5,6,0,7,6,4]]) 
d

array([list([1, 2, 4, 6, 7, 8, 9]), list([3, 4, 5, 6, 0, 7, 6, 4])],
      dtype=object)

In [17]:
d.shape

(2,)

In [7]:
e = np.array([[1,2,4,6,7,8,9], [3,4,5,6,0,7,6]])
print (e)

[[1 2 4 6 7 8 9]
 [3 4 5 6 0 7 6]]


In [46]:
# converting array to list
e.tolist()

[[1, 2, 4, 6, 7, 8, 9], [3, 4, 5, 6, 0, 7, 6]]

In [47]:
e.shape

(2, 7)

In [49]:
e[0,:]

array([1, 2, 4, 6, 7, 8, 9])

In [50]:
e[:, 5]

array([8, 7])

In [53]:
# [startindex, end index, step size]
e[ 1, 1: -1: 2]

array([4, 6, 7])

In [62]:
# Initializing a value to a row and column
e[1 , 4 ] = 50
e

array([[ 1,  2,  4,  6,  7,  8,  9],
       [ 3,  4,  5,  6, 50,  7,  6]])

In [64]:
e [0, : ]= 1
e

array([[ 1,  1,  1,  1,  1,  1,  1],
       [ 3,  4,  5,  6, 50,  7,  6]])

In [66]:
e[:, 3] = 7
e

array([[ 1,  1,  1,  7,  1,  1,  1],
       [ 3,  4,  5,  7, 50,  7,  6]])

In [68]:
e[:, 6] = [7,8]
e

array([[ 1,  1,  1,  7,  1,  1,  7],
       [ 3,  4,  5,  7, 50,  7,  8]])

###3 Dimension

In [73]:
Multi_dim = np.array([[[1,2,3], [4,5,6], [7,8,9]] , [[1,3,5], [6,7,8], [2,4,6]]])
Multi_dim

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 3, 5],
        [6, 7, 8],
        [2, 4, 6]]])

In [74]:
Multi_dim [1, 0, 2]

5

In [75]:
Multi_dim[:,1,:]

array([[4, 5, 6],
       [6, 7, 8]])

In [78]:
Multi_dim[:,1,0] = [50,50]
Multi_dim

array([[[ 1,  2,  3],
        [50,  5,  6],
        [ 7,  8,  9]],

       [[ 1,  3,  5],
        [50,  7,  8],
        [ 2,  4,  6]]])

### Initializing different types of arrays

In [79]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [80]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [84]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [93]:
np.zeros((2,3,4,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [100]:
# for ones
#indicate the datatype but by default it is float
np.ones((2,3), dtype= "int32")

array([[1, 1, 1],
       [1, 1, 1]])

In [10]:
#for all numbers
np.full((3,5), 100)


array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [11]:
full = np.full((3,5), 100)
full.dtype

dtype('int32')

In [12]:
full2 = np.full([1,2], 20)
full2

array([[20, 20]])

In [9]:
np.full_like(e, 7)

array([[7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7]])

In [36]:
np.empty([2, 2])

array([[1.28830546e-311, 1.33509389e-306],
       [6.23057349e-307, 4.22789837e-307]])

In [37]:
a = ([1,2,3], [4,5,6])                       
np.empty_like(a)

array([[1869570592, 1864379500, 1869182064],
       [ 174874990,  538976288,  538976288]])

In [20]:
#Random number 
np.random.rand(4, 2, 3, 2)

array([[[[0.02553196, 0.9941227 ],
         [0.66610343, 0.30171091],
         [0.37882126, 0.58646163]],

        [[0.09320924, 0.81391526],
         [0.09272843, 0.52766999],
         [0.0153297 , 0.27405904]]],


       [[[0.28632827, 0.62776811],
         [0.95444962, 0.14590315],
         [0.19612959, 0.46270788]],

        [[0.2886229 , 0.55287868],
         [0.63627538, 0.30469184],
         [0.17116205, 0.30801212]]],


       [[[0.13164726, 0.10444091],
         [0.79652931, 0.97973216],
         [0.43338291, 0.915723  ]],

        [[0.23829857, 0.57527057],
         [0.08700829, 0.02986865],
         [0.23253111, 0.31345005]]],


       [[[0.31384001, 0.04947175],
         [0.1440621 , 0.80482   ],
         [0.47486442, 0.30384395]],

        [[0.68186174, 0.95667424],
         [0.76842851, 0.31432534],
         [0.99023562, 0.94942069]]]])

In [22]:
# Random values of the equivalent of the sahpe of an array
np.random.random_sample(e.shape)

array([[0.78003777, 0.16185659, 0.9750165 , 0.5999423 , 0.04041314,
        0.58238814, 0.50587643],
       [0.65304115, 0.01613204, 0.59363392, 0.46967563, 0.45868804,
        0.69512728, 0.51990699]])

In [30]:
# Randome integer values
np.random.randint(9, size=(2,3))

array([[3, 4, 6],
       [5, 7, 8]])

In [14]:
# Arithmetic
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [15]:
a + 2

array([3, 4, 5, 6, 7])

In [16]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5])

In [17]:
2 * a

array([ 2,  4,  6,  8, 10])

In [18]:
# Taking sine of a
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [21]:
#Taking cosine of a
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [22]:
# tangent of a
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

## Linear Algebra

In [25]:
a =  np.ones((2,3))
print (a)

b = np.full((3,2), 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [26]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [27]:
# Determinat of Matrix
c =  np.identity(3)
np.linalg.det(c)

1.0

In [ ]:
##Statistic


In [31]:
stats = ([[1,2,3,4,7,9], [4,5,6,7,9,10]])
stats

[[1, 2, 3, 4, 7, 9], [4, 5, 6, 7, 9, 10]]

In [32]:
np.min(stats)

1

In [34]:
np.min(stats, axis = 1)

array([1, 4])

In [35]:
np.min(stats, axis = 0)

array([1, 2, 3, 4, 7, 9])

In [33]:
np.max(stats)

10

In [36]:
np.sum(stats)

67

### Reorganising Arrays

In [38]:
Old =  np.array([[1,2,3,4,7,9], [4,5,6,7,9,10]])
Old

array([[ 1,  2,  3,  4,  7,  9],
       [ 4,  5,  6,  7,  9, 10]])

In [44]:
New = Old.reshape((3,4))
New

array([[ 1,  2,  3,  4],
       [ 7,  9,  4,  5],
       [ 6,  7,  9, 10]])

#### Vector Stacking 

In [47]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([2,4,6,8,10])

np.vstack([v1,v2])

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10]])

In [48]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([2,4,6,8,10])

np.vstack([v1,v2,v2,v1])

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 2,  4,  6,  8, 10],
       [ 1,  2,  3,  4,  5]])

#### Horizontal stacking


In [52]:
h1 = np.ones((5,5))
h2 = np.zeros((5,1))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 0.]])